url: "https://xiaoyarap.github.io"
baseurl: "/blog"

# 站点基本信息
title: "小亚说"
description: "小亚说公众号提供专业护肤与健康营养服务"

author:
  name: "小亚说"
  url: "https://xiaoyarap.github.io/blog"
  sameAs:
    - "https://twitter.com/xiaoyarap"
    - "https://www.xiaohongshu.com/user/profile/5b8271aad24e100001eb3dc8"
    - "https://space.bilibili.com/602243031"

image: "https://xiaoyarap.github.io/blog/images/logo.jpg"

# 默认 front matter 设置
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author:
        name: "小亚说"
        url: "https://xiaoyarap.github.io/blog"
