# _config.yml
url: "https://xiaoyarap.github.io"
baseurl: "/blog"
theme: minima
# 站点基本信息
title: "小亚说"
description: "小亚说公众号提供专业护肤与健康营养服务"
author: "小亚说"
twitter: "https://twitter.com/xiaoyarap" 

# 默认的前置matter
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author:
        name: "小亚说"
        url: "https://xiaoyarap.github.io/blog"
